### PR TITLE
Adds workaround for free-form maps with propper typespec

### PR DESCRIPTION
**Pull request by mrmstn**
Hi @carrascoacd

This is my proposal for https://github.com/OpenAPITools/openapi-generator/pull/8159

Just let me know if this is what you expected. I used `map()` instead of `Map.t` since this is official notation according to https://hexdocs.pm/elixir/typespecs.html#basic-types

### CODE REVIEW

**Comment by carrascoacd** [comment]
Many thanks for taking care. This solves the problem that comes with the change of adding a `t()` for custom structs. But the real problem is the missing t().

How can we verify that this change will generate this example:
```
  @type t :: %__MODULE__{
    :"world" => World.t() | nil
  }
```

instead of this (notice the missing t()):
```
  @type t :: %__MODULE__{
    :"world" => World | nil
  }
```

Refer to this example to reproduce the problem [example.txt](https://github.com/OpenAPITools/openapi-generator/files/5672222/example.txt)

**Comment by mrmstn** [comment]
Thanks for the feedback, you're absolutely right, this has been mapped wrong all along. I've added the proper fix to my PR. 

Please see the examples to compare the results with your expectations.

**Comment by carrascoacd** [comment]
@mrmstn I think it looks great! Good job

**Comment by carrascoacd** [comment]
If you are ok I can merge the PR into the base, and then we can merge it to the base project, what do you think?

**Review by carrascoacd — APPROVED** [review]

**Comment by mrmstn** [comment]
Sounds great!

**Pull request merged**
